# Generated by Django 5.2.17 on 2026-09-14 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("slug", models.SlugField(blank=True, max_length=170, unique=True)),
                ("author", models.CharField(blank=True, max_length=150)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="One or two sentences shown on the Reading Club hub.",
                        max_length=255,
                    ),
                ),
                (
                    "overview",
                    models.TextField(
                        blank=True,
                        help_text="A longer introduction shown on the book's own page.",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("📚", "📚 Books"),
                            ("📖", "📖 Open book"),
                            ("🔍", "🔍 Magnifying glass"),
                            ("🎤", "🎤 Microphone"),
                            ("🎧", "🎧 Headphones"),
                            ("🗣️", "🗣️ Speaking head"),
                            ("💬", "💬 Speech bubble"),
                            ("✍️", "✍️ Writing hand"),
                            ("📝", "📝 Notes"),
                            ("🔤", "🔤 Letters"),
                            ("🧠", "🧠 Brain"),
                            ("🎯", "🎯 Target"),
                            ("🎭", "🎭 Theatre masks"),
                            ("🎨", "🎨 Palette"),
                            ("🎵", "🎵 Musical note"),
                            ("🧩", "🧩 Puzzle piece"),
                            ("🔬", "🔬 Microscope"),
                            ("🧭", "🧭 Compass"),
                            ("🧮", "🧮 Abacus"),
                            ("🗓️", "🗓️ Calendar"),
                            ("⭐", "⭐ Star"),
                            ("🌟", "🌟 Glowing star"),
                            ("🏆", "🏆 Trophy"),
                            ("🏅", "🏅 Medal"),
                            ("🎓", "🎓 Graduation cap"),
                            ("📣", "📣 Megaphone"),
                            ("🚀", "🚀 Rocket"),
                            ("🌍", "🌍 Globe"),
                        ],
                        default="📚",
                        help_text="Shown on the book's badge.",
                        max_length=8,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("#14213D", "Ink navy"),
                            ("#7A2438", "Maroon"),
                            ("#B8863B", "Gold"),
                            ("#24473E", "Green"),
                            ("#0B5E5E", "Teal"),
                            ("#1F6F8B", "Ocean blue"),
                            ("#7C3AED", "Purple"),
                            ("#8E44AD", "Violet"),
                            ("#9D174D", "Rose"),
                            ("#B03A2E", "Rust"),
                            ("#C2410C", "Amber"),
                            ("#374151", "Slate"),
                        ],
                        default="#B8863B",
                        help_text="Badge colour.",
                        max_length=7,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Unpublished books are hidden from the hub.",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(blank=True, upload_to="book/videos/%Y/%m/"),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="Use instead of a file upload for CDN-hosted video (e.g. Cloudflare R2, YouTube).",
                    ),
                ),
                ("video_caption", models.CharField(blank=True, max_length=150)),
                (
                    "video_duration_label",
                    models.CharField(
                        blank=True, help_text='e.g. "2-3 min"', max_length=30
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(blank=True, upload_to="book/audio/%Y/%m/"),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True,
                        help_text="Use instead of a file upload for CDN-hosted audio.",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="Chapter number within the term, e.g. 1"
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text='e.g. "The Beginning"', max_length=150),
                ),
                ("slug", models.SlugField(blank=True, max_length=120)),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="One line shown in the term's list of chapters.",
                        max_length=255,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="The chapter text. Plain paragraphs — a blank line starts a new one.",
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="ChapterResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "file",
                    models.FileField(
                        blank=True, upload_to="reading_club/resources/%Y/%m/"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Use instead of a file upload for an externally hosted resource.",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="reading_club.chapter",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text='e.g. "First Term"', max_length=100),
                ),
                ("slug", models.SlugField(blank=True, max_length=120)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="reading_club.book",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("book", "slug")},
            },
        ),
        migrations.AddField(
            model_name="chapter",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="reading_club.term",
            ),
        ),
        migrations.CreateModel(
            name="ChapterProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_entries",
                        to="reading_club.chapter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapter_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Chapter progress",
                "unique_together": {("user", "chapter")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="chapter",
            unique_together={("term", "number")},
        ),
    ]
