# Generated by Django 5.2.6 on 2026-09-23 20:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RadioProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("tagline", models.CharField(blank=True, max_length=220)),
                ("description", models.TextField(blank=True)),
                ("presenter", models.CharField(blank=True, max_length=120)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, upload_to="diction_radio/programs/%Y/%m/"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Sets when this programme plays in the station lineup.",
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "radio programme",
                "verbose_name_plural": "radio programmes",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="RadioEpisode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload an audio file, or provide a hosted audio link below.",
                        upload_to="diction_radio/audio/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["mp3", "m4a", "aac", "wav", "ogg", "flac", "mp4"]
                            )
                        ],
                    ),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True,
                        help_text="Use a hosted audio URL instead of uploading a file.",
                    ),
                ),
                (
                    "transcript",
                    models.TextField(
                        blank=True,
                        help_text="Optional transcript for listeners who prefer to read along.",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Playback order inside this programme."
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="diction_radio.radioprogram",
                    ),
                ),
            ],
            options={
                "verbose_name": "radio episode",
                "verbose_name_plural": "radio episodes",
                "ordering": ["program__order", "program_id", "order", "id"],
            },
        ),
    ]
