# Generated by Django 5.2.17 on 2026-09-14 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(help_text='e.g. "/iː/"', max_length=20)),
                ("name", models.CharField(help_text='e.g. "Long EE"', max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                (
                    "example_words",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated, e.g. seat, feel, sheep, clean, dream, reach, teach",
                        max_length=255,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Unpublished sounds are hidden from the 44 Academy grid.",
                    ),
                ),
            ],
            options={
                "ordering": ["category__order", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SoundCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Sound categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SentencePractice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(blank=True, upload_to="book/audio/%Y/%m/"),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True,
                        help_text="Use instead of a file upload for CDN-hosted audio.",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("sentence", models.TextField()),
                (
                    "sound",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentence_practices",
                        to="book.sound",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sentence practice",
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Passage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(blank=True, upload_to="book/audio/%Y/%m/"),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True,
                        help_text="Use instead of a file upload for CDN-hosted audio.",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=150)),
                ("body", models.TextField()),
                (
                    "sound",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passages",
                        to="book.sound",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MinimalPairsAudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(blank=True, upload_to="book/audio/%Y/%m/"),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True,
                        help_text="Use instead of a file upload for CDN-hosted audio.",
                    ),
                ),
                (
                    "sound",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="minimal_pairs_audio",
                        to="book.sound",
                    ),
                ),
            ],
            options={
                "verbose_name": "Minimal pairs audio (one per sound)",
                "verbose_name_plural": "Minimal pairs audio (one per sound)",
            },
        ),
        migrations.CreateModel(
            name="MinimalPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("word_a", models.CharField(max_length=100)),
                ("word_b", models.CharField(max_length=100)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="What makes these two easy to confuse."
                    ),
                ),
                (
                    "sound",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="minimal_pairs",
                        to="book.sound",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Minimal pairs",
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExternalLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=150)),
                ("url", models.URLField()),
                ("description", models.TextField(blank=True)),
                (
                    "sound",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_links",
                        to="book.sound",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(blank=True, upload_to="book/audio/%Y/%m/"),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True,
                        help_text="Use instead of a file upload for CDN-hosted audio.",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=150)),
                (
                    "script",
                    models.TextField(
                        help_text='One line per turn, e.g. "A: Good morning!"'
                    ),
                ),
                (
                    "sound",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="book.sound",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Articulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(blank=True, upload_to="book/videos/%Y/%m/"),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="Use instead of a file upload for CDN-hosted video (e.g. Cloudflare R2, YouTube).",
                    ),
                ),
                ("video_caption", models.CharField(blank=True, max_length=150)),
                (
                    "video_duration_label",
                    models.CharField(
                        blank=True, help_text='e.g. "2-3 min"', max_length=30
                    ),
                ),
                (
                    "trap_heading",
                    models.CharField(default="The Nigerian Trap", max_length=100),
                ),
                (
                    "trap_text",
                    models.TextField(
                        blank=True,
                        help_text="The common mistake Nigerian learners make with this sound.",
                    ),
                ),
                (
                    "mouth_position_text",
                    models.TextField(
                        blank=True,
                        help_text="How to shape the mouth, lips and tongue for this sound.",
                    ),
                ),
                (
                    "practice_words",
                    models.CharField(
                        blank=True,
                        help_text="Short list shown on the lesson page, e.g. seat, feel, sheep",
                        max_length=255,
                    ),
                ),
                (
                    "qr_code",
                    models.CharField(blank=True, editable=False, max_length=30),
                ),
                (
                    "qr_label",
                    models.CharField(blank=True, editable=False, max_length=150),
                ),
                (
                    "sound",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articulation",
                        to="book.sound",
                    ),
                ),
            ],
            options={
                "verbose_name": "Articulation (Lens tab)",
                "verbose_name_plural": "Articulation (Lens tab)",
            },
        ),
        migrations.AddField(
            model_name="sound",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sounds",
                to="book.soundcategory",
            ),
        ),
        migrations.CreateModel(
            name="TongueTwister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(blank=True, upload_to="book/audio/%Y/%m/"),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True,
                        help_text="Use instead of a file upload for CDN-hosted audio.",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("text", models.TextField()),
                (
                    "sound",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tongue_twisters",
                        to="book.sound",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tongue twister",
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WordBankEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(blank=True, upload_to="book/audio/%Y/%m/"),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True,
                        help_text="Use instead of a file upload for CDN-hosted audio.",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("word", models.CharField(max_length=100)),
                (
                    "spelling_pattern",
                    models.TextField(
                        blank=True,
                        help_text='e.g. "ee, ea and ey can all spell this sound."',
                    ),
                ),
                (
                    "sound",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_bank_entries",
                        to="book.sound",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Word bank entries",
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
    ]
