# Generated by Django 5.2.17 on 2026-09-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhonemeAudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(blank=True, upload_to="book/audio/%Y/%m/"),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True,
                        help_text="Use instead of a file upload for CDN-hosted audio.",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text='The chart keyword, e.g. "fleece".',
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                (
                    "spoken_text",
                    models.CharField(
                        blank=True, help_text="What the recording says.", max_length=255
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("generated", "Generated with ElevenLabs"),
                            ("uploaded", "Uploaded by an admin"),
                        ],
                        default="generated",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Phonemic chart audio",
                "verbose_name_plural": "Phonemic chart audio",
                "ordering": ["key"],
            },
        ),
    ]
