# Generated by Django 5.2.17 on 2026-09-17 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_video_poster"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadAlongTiming",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                ("fingerprint", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("working", "Working"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="working",
                        max_length=10,
                    ),
                ),
                ("engine", models.CharField(blank=True, max_length=20)),
                (
                    "words",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[[word, start, end], …] in seconds.",
                    ),
                ),
                ("error", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "read-along timing",
                "unique_together": {("content_type", "object_id")},
            },
        ),
    ]
