# Generated by Django 5.2.17 on 2026-09-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_readalongtiming"),
    ]

    operations = [
        migrations.AddField(
            model_name="readalongtiming",
            name="duration",
            field=models.FloatField(
                blank=True, help_text="Length of the recording, in seconds.", null=True
            ),
        ),
        migrations.AddField(
            model_name="readalongtiming",
            name="quality",
            field=models.FloatField(
                blank=True,
                help_text="How much of the text the recording actually says, 0–1. Low means the recording and the text don't match.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="readalongtiming",
            name="speech",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[[start, end], …]: when someone is actually speaking, so the highlight waits through pauses.",
            ),
        ),
    ]
