# Generated by Django 5.2.6 on 2026-09-21 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_read_along_speech"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(blank=True, upload_to="book/videos/%Y/%m/"),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="Use instead of a file upload for CDN-hosted video (e.g. Cloudflare R2, YouTube).",
                    ),
                ),
                ("video_caption", models.CharField(blank=True, max_length=150)),
                (
                    "video_duration_label",
                    models.CharField(
                        blank=True, help_text='e.g. "2-3 min"', max_length=30
                    ),
                ),
                (
                    "video_poster",
                    models.ImageField(
                        blank=True,
                        help_text="The still shown before the video plays. Taken from the video automatically; upload your own to replace it.",
                        upload_to="posters/%Y/%m/",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("lens", "Lens"),
                            ("word-bank", "Word Bank"),
                            ("sentence-practice", "Sentence Practice"),
                            ("passage", "Passage"),
                            ("conversations", "Conversations"),
                            ("twisters", "Twisters"),
                            ("minimal-pairs", "Min. Pairs"),
                            ("external-links", "External Links"),
                        ],
                        default="lens",
                        help_text="Which tab of the lesson this video appears on.",
                        max_length=30,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers show first."
                    ),
                ),
                (
                    "sound",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="book.sound",
                    ),
                ),
            ],
            options={
                "verbose_name": "tab video",
                "verbose_name_plural": "tab videos",
                "ordering": ["section", "order", "pk"],
            },
        ),
    ]
