# Generated by Django 5.2.6 on 2026-09-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0006_sectionvideo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articulation",
            options={
                "verbose_name": "Articulation (Trick tab)",
                "verbose_name_plural": "Articulation (Trick tab)",
            },
        ),
        migrations.AlterModelOptions(
            name="wordbankentry",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "word list entry",
                "verbose_name_plural": "Word list entries",
            },
        ),
        migrations.AlterField(
            model_name="sectionvideo",
            name="section",
            field=models.CharField(
                choices=[
                    ("lens", "Trick"),
                    ("word-bank", "Word List"),
                    ("sentence-practice", "Sentence Practice"),
                    ("passage", "Passage"),
                    ("conversations", "Conversations"),
                    ("twisters", "Twisters"),
                    ("minimal-pairs", "Min. Pairs"),
                    ("external-links", "External Links"),
                ],
                default="lens",
                help_text="Which tab of the lesson this video appears on.",
                max_length=30,
            ),
        ),
    ]
