# Generated by Django 5.2.6 on 2026-09-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0007_alter_articulation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="soundcategory",
            name="programme",
            field=models.CharField(
                choices=[
                    ("academy", "44 Academy"),
                    ("tricks", "Tricks to Sound Fluent"),
                ],
                db_index=True,
                default="academy",
                help_text="Which programme this group's lessons belong to.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sound",
            name="symbol",
            field=models.CharField(
                help_text="The badge on the lesson's tile — a sound's symbol such as \"/iː/\", or a short mark for a trick.",
                max_length=20,
            ),
        ),
    ]
