# Generated by Django 5.2.6 on 2026-09-22 13:29

from django.db import migrations, models


def one_list_of_tricks(apps, schema_editor):
    """Tricks to Sound Fluent no longer has groups: put every trick into one
    group, numbered 1, 2, 3… in the order they were shown, and drop the rest."""
    SoundCategory = apps.get_model("book", "SoundCategory")
    Sound = apps.get_model("book", "Sound")
    groups = list(SoundCategory.objects.filter(programme="tricks").order_by("order", "name", "pk"))
    if not groups:
        return
    keep = groups[0]
    tricks = Sound.objects.filter(category__programme="tricks").order_by("category__order", "category__name", "order", "name")
    for number, trick in enumerate(tricks, start=1):
        Sound.objects.filter(pk=trick.pk).update(category=keep, order=number)
    SoundCategory.objects.filter(pk__in=[g.pk for g in groups[1:]]).delete()
    SoundCategory.objects.filter(pk=keep.pk).update(name="Tricks", order=0)


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0008_soundcategory_programme_alter_sound_symbol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sound",
            name="symbol",
            field=models.CharField(
                blank=True,
                help_text='The sound\'s symbol, such as "/iː/". Optional for a trick: its badge, e.g. "-age".',
                max_length=20,
            ),
        ),
        migrations.RunPython(one_list_of_tricks, migrations.RunPython.noop),
    ]
