# Generated by Django 5.2.6 on 2026-09-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0009_tricks_without_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="minimalpair",
            name="audio_a_file",
            field=models.FileField(
                blank=True,
                upload_to="book/audio/%Y/%m/",
                verbose_name="Audio: first word (upload)",
            ),
        ),
        migrations.AddField(
            model_name="minimalpair",
            name="audio_a_url",
            field=models.URLField(
                blank=True,
                help_text="Instead of an upload, a link to hosted audio.",
                verbose_name="Audio: first word (link)",
            ),
        ),
        migrations.AddField(
            model_name="minimalpair",
            name="audio_b_file",
            field=models.FileField(
                blank=True,
                upload_to="book/audio/%Y/%m/",
                verbose_name="Audio: second word (upload)",
            ),
        ),
        migrations.AddField(
            model_name="minimalpair",
            name="audio_b_url",
            field=models.URLField(
                blank=True,
                help_text="Instead of an upload, a link to hosted audio.",
                verbose_name="Audio: second word (link)",
            ),
        ),
    ]
