# Generated by Django 5.2.6 on 2026-09-28 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0010_minimal_pair_audio"),
    ]

    operations = [
        migrations.AddField(
            model_name="sound",
            name="card_image",
            field=models.ImageField(
                blank=True,
                help_text="The picture behind this lesson's tile in the list of sounds (or tricks). Wide pictures work best; the words sit on a soft shade so they stay easy to read. Leave empty for the plain card.",
                upload_to="book/cards/sounds/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg", "webp"]
                    )
                ],
                verbose_name="Card background image",
            ),
        ),
    ]
