# Generated by Django 5.2.17 on 2026-09-15 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("quick_words", "0003_word_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("classic", "Classic Clash"),
                            ("blitz", "60-Second Blitz"),
                            ("survival", "Survival"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("expert", "Very difficult"),
                        ],
                        max_length=20,
                    ),
                ),
                ("seed", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "In play"), ("finished", "Finished")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("correct", models.PositiveIntegerField(default=0)),
                ("wrong", models.PositiveIntegerField(default=0)),
                ("streak", models.PositiveIntegerField(default=0)),
                ("best_streak", models.PositiveIntegerField(default=0)),
                ("lives", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clash_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Matches",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("kind", models.CharField(max_length=30)),
                ("prompt", models.TextField(blank=True)),
                ("prompt_detail", models.CharField(blank=True, max_length=255)),
                ("options", models.JSONField(blank=True, default=list)),
                ("answer", models.CharField(max_length=255)),
                ("seconds", models.PositiveIntegerField(default=0)),
                ("shown_at", models.DateTimeField(auto_now_add=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("given", models.CharField(blank=True, max_length=255)),
                ("is_correct", models.BooleanField(null=True)),
                ("timed_out", models.BooleanField(default=False)),
                ("points", models.IntegerField(default=0)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="clash.match",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="quick_words.quickword",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
                "unique_together": {("match", "number")},
            },
        ),
    ]
