# Generated by Django 5.2.17 on 2026-09-14 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LibraryArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="One or two sentences shown in search results and listings.",
                        max_length=300,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="The full article. Plain paragraphs — a blank line starts a new one."
                    ),
                ),
                (
                    "source_credit",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Adapted from the Oxford Guide to English Grammar"',
                        max_length=255,
                    ),
                ),
                (
                    "external_link",
                    models.URLField(
                        blank=True, help_text="Optional — a place to read further."
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category__order", "order", "title"],
            },
        ),
        migrations.CreateModel(
            name="LibraryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="One line shown under the category name.",
                        max_length=255,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Library categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="LibraryTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LibraryAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "file",
                    models.FileField(
                        blank=True, upload_to="library/attachments/%Y/%m/"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Use instead of a file upload for an externally hosted document.",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="reference_library.libraryarticle",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="libraryarticle",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="reference_library.librarycategory",
            ),
        ),
        migrations.AddField(
            model_name="libraryarticle",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="articles", to="reference_library.librarytag"
            ),
        ),
    ]
