# Generated by Django 5.2.6 on 2026-09-23 14:53

import django.core.validators
from django.db import migrations, models


CARD_KEYS = [
    "progress-echospell", "progress-etiquette", "progress-academy",
    "progress-tricks", "progress-tutor", "progress-modules",
    "tool-learning-modules", "tool-echospell", "tool-quick-words",
    "tool-assessments", "tool-clash", "tool-tutor",
    "tool-daily-practice", "tool-academy", "tool-tricks",
    "tool-reading-club", "tool-reference-library",
]

def seed_card_slots(apps, schema_editor):
    CardImage = apps.get_model("accounts", "DashboardCardImage")
    CardImage.objects.using(schema_editor.connection.alias).bulk_create(
        [CardImage(key=key) for key in CARD_KEYS], ignore_conflicts=True
    )


def remove_card_slots(apps, schema_editor):
    CardImage = apps.get_model("accounts", "DashboardCardImage")
    CardImage.objects.using(schema_editor.connection.alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardCardImage",
            fields=[
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("progress-echospell", "EchoSpell progress card"),
                            ("progress-etiquette", "Etiquette Advantage progress card"),
                            ("progress-academy", "44 Academy progress card"),
                            ("progress-tricks", "Tricks to Sound Fluent progress card"),
                            ("progress-tutor", "AI Reading Tutor progress card"),
                            ("progress-modules", "My Modules progress card"),
                            ("tool-learning-modules", "Learning Modules tool card"),
                            ("tool-echospell", "EchoSpell tool card"),
                            ("tool-quick-words", "Quick Words tool card"),
                            ("tool-assessments", "Assessments tool card"),
                            ("tool-clash", "Diction Clash tool card"),
                            ("tool-tutor", "AI Reading Tutor tool card"),
                            ("tool-daily-practice", "Daily Practice tool card"),
                            ("tool-academy", "44 Academy tool card"),
                            ("tool-tricks", "Tricks to Sound Fluent tool card"),
                            ("tool-reading-club", "Reading Club tool card"),
                            ("tool-reference-library", "Reference Library tool card"),
                        ],
                        editable=False,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload an image from this device. Wide images work best. Leave empty to use the card's built-in colors.",
                        upload_to="dashboard/cards/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg", "webp"]
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "dashboard card image",
                "verbose_name_plural": "dashboard card images",
                "ordering": ["key"],
            },
        ),
        migrations.RunPython(seed_card_slots, remove_card_slots),
    ]
