# Generated by Django 5.2.6 on 2026-09-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_dashboard_card_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Optional. Students can sign in with this instead of an email: letters, numbers, dots and dashes.",
                max_length=40,
                null=True,
                unique=True,
            ),
        ),
    ]
