# Generated by Django 5.2.6 on 2026-09-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_device_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="additional_levels",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Other levels they also teach or study, besides the main one above.",
                max_length=255,
            ),
        ),
    ]
