# Generated by Django 5.2.6 on 2026-10-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_password_help"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="simple_home",
            field=models.BooleanField(
                default=False,
                help_text="Individual learners only: show the simple one-button home instead of the full dashboard.",
            ),
        ),
    ]
