# Generated by Django 5.2.6 on 2026-10-08 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_user_simple_home"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrownUpSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pin_hash",
                    models.CharField(blank=True, editable=False, max_length=128),
                ),
                (
                    "failed_tries",
                    models.PositiveSmallIntegerField(default=0, editable=False),
                ),
                (
                    "locked_until",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "weekly_email",
                    models.BooleanField(
                        default=True,
                        help_text="Send the weekly summary (or, for a teacher, the weekly 'Needs help' email).",
                    ),
                ),
                (
                    "last_summary_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grown_up",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "grown-up settings",
                "verbose_name_plural": "grown-up settings",
            },
        ),
    ]
