# Generated by Django 5.2.17 on 2026-09-19 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorPassage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Pre-Level", "Pre-Level"),
                            ("Level 1", "Level 1"),
                            ("Level 2", "Level 2"),
                            ("Level 3", "Level 3"),
                            ("Level 4", "Level 4"),
                            ("Level 5", "Level 5"),
                            ("Level 6", "Level 6"),
                            ("Level 7", "Level 7"),
                            ("Level 8", "Level 8"),
                            ("Level 9", "Level 9"),
                            ("Level 10", "Level 10"),
                            ("Level 11", "Level 11"),
                            ("Level 12", "Level 12"),
                        ],
                        default="Level 1",
                        help_text="The level this passage is written for. The tutor measures reading level against it.",
                        max_length=100,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="The passage. Keep it to what a learner can read in two or three minutes; blank lines separate paragraphs."
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="One line shown on the passage card.",
                        max_length=200,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "tutor passage",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="TutorSpeech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("text", models.CharField(max_length=600)),
                ("audio", models.FileField(upload_to="tutor/speech/%Y/%m/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "tutor speech",
                "verbose_name_plural": "tutor speech",
            },
        ),
        migrations.CreateModel(
            name="TutorSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("passage_level", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("reading", "Reading"), ("done", "Finished")],
                        default="reading",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("sentences", models.JSONField(blank=True, default=dict)),
                ("practised", models.JSONField(blank=True, default=dict)),
                ("checks", models.PositiveIntegerField(default=0)),
                ("sentences_read", models.PositiveIntegerField(default=0)),
                ("sentences_total", models.PositiveIntegerField(default=0)),
                ("words_total", models.PositiveIntegerField(default=0)),
                ("words_correct", models.PositiveIntegerField(default=0)),
                ("accuracy", models.FloatField(blank=True, null=True)),
                (
                    "wcpm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="words correct per minute"
                    ),
                ),
                ("reading_seconds", models.FloatField(blank=True, null=True)),
                (
                    "band",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("independent", "Reads it comfortably"),
                            ("instructional", "Right level to learn from"),
                            ("frustration", "Too hard for now"),
                        ],
                        max_length=15,
                    ),
                ),
                ("reading_level", models.CharField(blank=True, max_length=100)),
                ("mistakes", models.JSONField(blank=True, default=list)),
                ("patterns", models.JSONField(blank=True, default=list)),
                ("feedback", models.JSONField(blank=True, default=dict)),
                (
                    "passage",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="tutor.tutorpassage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "tutor session",
                "ordering": ["-started_at"],
            },
        ),
    ]
