# Generated by Django 5.2.6 on 2026-09-22 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutor", "0002_starter_passages"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorVoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='What the learner sees, e.g. "Yela".', max_length=60
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("female", "Female"), ("male", "Male")],
                        default="female",
                        max_length=10,
                    ),
                ),
                (
                    "avatar",
                    models.CharField(
                        choices=[
                            ("yela", "Yela — braids, gold hoops"),
                            ("ada", "Ada — short curls, glasses"),
                            ("nia", "Nia — headwrap"),
                            ("kayode", "Kayode — short hair, beard"),
                            ("tobi", "Tobi — fade, warm smile"),
                            ("orb", "No face — a listening orb"),
                        ],
                        default="yela",
                        help_text="The face shown while this voice speaks.",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text='One line, e.g. "Warm and steady, British English".',
                        max_length=120,
                    ),
                ),
                (
                    "voice_id",
                    models.CharField(
                        blank=True,
                        help_text="The ElevenLabs voice. Leave blank to use the site's own voice.",
                        max_length=64,
                    ),
                ),
                (
                    "sample_text",
                    models.CharField(
                        blank=True,
                        help_text="What this voice says when a learner presses Hear me. Blank uses a standard line.",
                        max_length=200,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="The one new learners start with."
                    ),
                ),
            ],
            options={
                "verbose_name": "tutor voice",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TutorChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor_choice",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chosen_by",
                        to="tutor.tutorvoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "chosen tutor voice",
                "verbose_name_plural": "chosen tutor voices",
            },
        ),
    ]
