# Generated by Django 5.2.6 on 2026-09-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutor", "0004_starter_voices"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorvoice",
            name="portrait",
            field=models.ImageField(
                blank=True,
                help_text="A picture of this tutor — a 3D character portrait looks best. Square, 512×512 or larger. Leave empty to use the drawn face above.",
                upload_to="tutor/faces/%Y/%m/",
            ),
        ),
    ]
