# Generated by Django 5.2.6 on 2026-09-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutor", "0005_voice_portrait"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorvoice",
            name="voice_id",
            field=models.CharField(
                blank=True,
                help_text="Legacy field; generated tutor audio always uses the project-wide voice.",
                max_length=64,
            ),
        ),
    ]
