# Generated by Django 5.2.17 on 2026-09-14 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("words", "Word cards"),
                            ("passage", "Passage reading"),
                            ("dialogue", "Dialogue"),
                        ],
                        default="words",
                        help_text="What content this card needs: a word list, a passage, or a dialogue.",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="One line shown on the 'choose a card' screen.",
                        max_length=255,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("📚", "📚 Books"),
                            ("📖", "📖 Open book"),
                            ("🔍", "🔍 Magnifying glass"),
                            ("🎤", "🎤 Microphone"),
                            ("🎧", "🎧 Headphones"),
                            ("🗣️", "🗣️ Speaking head"),
                            ("💬", "💬 Speech bubble"),
                            ("✍️", "✍️ Writing hand"),
                            ("📝", "📝 Notes"),
                            ("🔤", "🔤 Letters"),
                            ("🧠", "🧠 Brain"),
                            ("🎯", "🎯 Target"),
                            ("🎭", "🎭 Theatre masks"),
                            ("🎨", "🎨 Palette"),
                            ("🎵", "🎵 Musical note"),
                            ("🧩", "🧩 Puzzle piece"),
                            ("🔬", "🔬 Microscope"),
                            ("🧭", "🧭 Compass"),
                            ("🧮", "🧮 Abacus"),
                            ("🗓️", "🗓️ Calendar"),
                            ("⭐", "⭐ Star"),
                            ("🌟", "🌟 Glowing star"),
                            ("🏆", "🏆 Trophy"),
                            ("🏅", "🏅 Medal"),
                            ("🎓", "🎓 Graduation cap"),
                            ("📣", "📣 Megaphone"),
                            ("🚀", "🚀 Rocket"),
                            ("🌍", "🌍 Globe"),
                        ],
                        default="✏️",
                        max_length=8,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("#14213D", "Ink navy"),
                            ("#7A2438", "Maroon"),
                            ("#B8863B", "Gold"),
                            ("#24473E", "Green"),
                            ("#0B5E5E", "Teal"),
                            ("#1F6F8B", "Ocean blue"),
                            ("#7C3AED", "Purple"),
                            ("#8E44AD", "Violet"),
                            ("#9D174D", "Rose"),
                            ("#B03A2E", "Rust"),
                            ("#C2410C", "Amber"),
                            ("#374151", "Slate"),
                        ],
                        default="#1B3A6B",
                        max_length=7,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Dialogue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(blank=True, upload_to="book/audio/%Y/%m/"),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True,
                        help_text="Use instead of a file upload for CDN-hosted audio.",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="Group number within the level, e.g. 1"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional, shown alongside the number.",
                        max_length=150,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=120)),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="DialogueLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "speaker",
                    models.CharField(
                        default="A", help_text='e.g. "A" or "B"', max_length=20
                    ),
                ),
                ("text", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "dialogue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="echospell.dialogue",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="dialogue",
            name="group",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dialogue",
                to="echospell.group",
            ),
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                (
                    "age_range",
                    models.CharField(
                        blank=True, help_text='e.g. "Nursery 1-2"', max_length=100
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Unpublished levels are hidden from the hub.",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Which cards are available for every group in this level.",
                        related_name="levels",
                        to="echospell.category",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="group",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="echospell.level",
            ),
        ),
        migrations.CreateModel(
            name="Passage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(blank=True, upload_to="book/audio/%Y/%m/"),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True,
                        help_text="Use instead of a file upload for CDN-hosted audio.",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=150)),
                (
                    "body",
                    models.TextField(
                        blank=True, help_text="Ideally built from this group's words."
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passage",
                        to="echospell.group",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(blank=True, upload_to="book/videos/%Y/%m/"),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="Use instead of a file upload for CDN-hosted video (e.g. Cloudflare R2, YouTube).",
                    ),
                ),
                ("video_caption", models.CharField(blank=True, max_length=150)),
                (
                    "video_duration_label",
                    models.CharField(
                        blank=True, help_text='e.g. "2-3 min"', max_length=30
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(blank=True, upload_to="book/audio/%Y/%m/"),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True,
                        help_text="Use instead of a file upload for CDN-hosted audio.",
                    ),
                ),
                ("word", models.CharField(max_length=100)),
                (
                    "ipa",
                    models.CharField(
                        blank=True,
                        help_text='Phonemic transcription, e.g. "/əˈtʃiːv/"',
                        max_length=100,
                    ),
                ),
                ("definition", models.CharField(blank=True, max_length=255)),
                ("example_sentence", models.CharField(blank=True, max_length=255)),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="echospell/words/%Y/%m/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to="echospell.group",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="GroupProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_entries",
                        to="echospell.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="echospell_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Group progress",
                "unique_together": {("user", "group")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="group",
            unique_together={("level", "number")},
        ),
    ]
