# Generated by Django 5.2.17 on 2026-09-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("echospell", "0002_seed_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="word",
            field=models.CharField(
                help_text='One word, or several sharing this card\'s audio — separate with commas, e.g. "seat, feel, sheep".',
                max_length=255,
                verbose_name="word or words",
            ),
        ),
    ]
