# Generated by Django 5.2.17 on 2026-09-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("echospell", "0003_alter_word_word"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="word",
            field=models.TextField(
                help_text='One word, or several sharing this card\'s audio — one per line (numbering is optional, so "1. seat" and "seat" both work), e.g.:\n1. seat\n2. feel\n3. sheep',
                verbose_name="word or words",
            ),
        ),
    ]
