# Generated by Django 5.2.17 on 2026-09-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("echospell", "0005_cardlesson"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cardlesson",
            options={"ordering": ["group", "category", "order", "id"]},
        ),
        migrations.AlterUniqueTogether(
            name="cardlesson",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cardlesson",
            name="definition",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="cardlesson",
            name="example_sentence",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="cardlesson",
            name="image",
            field=models.ImageField(blank=True, upload_to="echospell/lessons/%Y/%m/"),
        ),
        migrations.AddField(
            model_name="cardlesson",
            name="ipa",
            field=models.CharField(
                blank=True,
                help_text='Phonemic transcription, e.g. "/əˈtʃiːv/"',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="cardlesson",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cardlesson",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cardlesson",
            name="word",
            field=models.TextField(
                blank=True,
                help_text='One word, or several sharing this card\'s audio — one per line (numbering is optional, so "1. seat" and "seat" both work), e.g.:\n1. seat\n2. feel\n3. sheep',
                verbose_name="word or words",
            ),
        ),
        migrations.AlterField(
            model_name="cardlesson",
            name="body",
            field=models.TextField(
                blank=True,
                help_text="Optional teaching notes or instructions for this card.",
            ),
        ),
        migrations.DeleteModel(
            name="Word",
        ),
    ]
