# Generated by Django 5.2.17 on 2026-09-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("echospell", "0006_alter_cardlesson_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="level",
            name="name",
            field=models.CharField(
                choices=[
                    ("Pre-Level", "Pre-Level"),
                    ("Level 1", "Level 1"),
                    ("Level 2", "Level 2"),
                    ("Level 3", "Level 3"),
                    ("Level 4", "Level 4"),
                    ("Level 5", "Level 5"),
                    ("Level 6", "Level 6"),
                    ("Level 7", "Level 7"),
                    ("Level 8", "Level 8"),
                    ("Level 9", "Level 9"),
                    ("Level 10", "Level 10"),
                    ("Level 11", "Level 11"),
                    ("Level 12", "Level 12"),
                ],
                max_length=100,
            ),
        ),
    ]
