# Generated by Django 5.2.17 on 2026-09-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("echospell", "0008_alter_group_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardlesson",
            name="definition",
            field=models.TextField(
                blank=True,
                help_text="The meaning of each word above, in the same order — one per line (numbering is optional), e.g.:\n1. a place to sit\n2. to touch gently\n3. a farm animal. For Vocabulary cards, this is matched to the words by position.",
                verbose_name="meaning or meanings",
            ),
        ),
    ]
