# Generated by Django 5.2.17 on 2026-09-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("echospell", "0013_cardposition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="kind",
            field=models.CharField(
                choices=[
                    ("transcription", "🔤  Transcription — Typed answer"),
                    ("dictation", "🎧  Spelling dictation — Typed answer"),
                    ("missing-letters", "✏️  Missing letters — Typed answer"),
                    ("word-scramble", "🧩  Puzzle — word scramble — Typed answer"),
                    ("syllable-count", "🔢  Syllable count — Typed answer"),
                    ("spelling-fix", "🩹  Correct the spelling — Typed answer"),
                    ("word-to-sentence", "📝  Use it in a sentence — Typed answer"),
                    ("listen-choose", "🎧  Listen and choose — Multiple choice"),
                    ("minimal-pairs", "👂  Minimal pairs — Multiple choice"),
                    ("odd-one-out", "🔍  Odd one out — Multiple choice"),
                    ("stress-placement", "📈  Word stress — Multiple choice"),
                    ("silent-letter", "🤫  Silent letters — Multiple choice"),
                    ("homophones", "👯  Homophones — Multiple choice"),
                    ("rhyme-match", "🎵  Rhyme match — Multiple choice"),
                    ("sound-to-symbol", "🔣  Sound to symbol — Multiple choice"),
                    ("picture-word", "🖼️  Picture and word — Multiple choice"),
                    ("sound-sort", "🗂️  Sound sort — Drag into boxes"),
                    ("sentence-builder", "🧱  Sentence builder — Drag into order"),
                    ("listen-and-number", "🧮  Listen and number — Drag into order"),
                    ("read-aloud", "🎙️  Read aloud — Record your voice"),
                    ("repeat-after", "🔁  Listen and repeat — Record your voice"),
                    ("tongue-twister", "🌀  Tongue twister — Record your voice"),
                ],
                default="transcription",
                help_text="What learners do, and how their answers get marked.",
                max_length=40,
            ),
        ),
    ]
