# Generated by Django 5.2.6 on 2026-09-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("echospell", "0014_alter_activity_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardlesson",
            name="quick_audio_file",
            field=models.FileField(
                blank=True,
                help_text="The same word at normal speaking speed. Optional — the Full one is enough on its own.",
                upload_to="echospell/lessons/quick/%Y/%m/",
                verbose_name="Quick recording",
            ),
        ),
        migrations.AddField(
            model_name="cardlesson",
            name="quick_audio_url",
            field=models.URLField(
                blank=True,
                help_text="Use instead of the Quick upload for audio hosted elsewhere.",
                verbose_name="Quick recording link",
            ),
        ),
        migrations.AlterField(
            model_name="cardlesson",
            name="audio_file",
            field=models.FileField(
                blank=True,
                help_text="The whole word said slowly and clearly, on its own.",
                upload_to="book/audio/%Y/%m/",
                verbose_name="Full recording",
            ),
        ),
        migrations.AlterField(
            model_name="cardlesson",
            name="audio_url",
            field=models.URLField(
                blank=True,
                help_text="Use instead of the Full upload for audio hosted elsewhere.",
                verbose_name="Full recording link",
            ),
        ),
    ]
