# Generated by Django 5.2.6 on 2026-09-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("echospell", "0015_cardlesson_quick_audio_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityattempt",
            name="teacher_audio_feedback",
            field=models.FileField(
                blank=True,
                help_text="Audio feedback recorded by the teacher.",
                upload_to="teacher-feedback/%Y/%m/",
            ),
        ),
    ]
