# Generated by Django 5.2.6 on 2026-09-28 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("echospell", "0017_activityresponse_awarded_mark"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="card_image",
            field=models.ImageField(
                blank=True,
                help_text="The picture behind this group's card on its level's page. Wide pictures work best; the words sit on a soft shade so they stay easy to read. Leave empty for the plain card.",
                upload_to="echospell/cards/groups/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg", "webp"]
                    )
                ],
                verbose_name="Card background image",
            ),
        ),
        migrations.AddField(
            model_name="level",
            name="card_image",
            field=models.ImageField(
                blank=True,
                help_text="The picture behind this level's card on the EchoSpell page. Wide pictures work best; the words sit on a soft shade so they stay easy to read. Leave empty for the plain card.",
                upload_to="echospell/cards/levels/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg", "webp"]
                    )
                ],
                verbose_name="Card background image",
            ),
        ),
    ]
