# Generated by Django 5.2.6 on 2026-09-28 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("echospell", "0018_group_card_image_level_card_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardLessonQuick",
            fields=[],
            options={
                "verbose_name": "card lesson (quick recording)",
                "verbose_name_plural": "card lessons (quick recording)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("echospell.cardlesson",),
        ),
    ]
