# Generated by Django 5.2.6 on 2026-10-08 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("echospell", "0019_card_lesson_quick"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupStepsSeen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cards_seen",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Category ids opened, in the order first opened.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="echospell.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="echospell_steps_seen",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "group steps seen",
                "verbose_name_plural": "group steps seen",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "group"), name="one_steps_seen_per_group"
                    )
                ],
            },
        ),
    ]
