# Generated by Django 5.2.6 on 2026-09-26 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DialogueLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Pre-Level", "Pre-Level"),
                            ("Level 1", "Level 1"),
                            ("Level 2", "Level 2"),
                            ("Level 3", "Level 3"),
                            ("Level 4", "Level 4"),
                            ("Level 5", "Level 5"),
                            ("Level 6", "Level 6"),
                            ("Level 7", "Level 7"),
                            ("Level 8", "Level 8"),
                            ("Level 9", "Level 9"),
                            ("Level 10", "Level 10"),
                            ("Level 11", "Level 11"),
                            ("Level 12", "Level 12"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="One line shown on the level's card.",
                        max_length=255,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Unpublished levels are hidden from learners.",
                    ),
                ),
            ],
            options={
                "verbose_name": "level",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Dialogue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(blank=True, upload_to="book/videos/%Y/%m/"),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="Use instead of a file upload for CDN-hosted video (e.g. Cloudflare R2, YouTube).",
                    ),
                ),
                ("video_caption", models.CharField(blank=True, max_length=150)),
                (
                    "video_duration_label",
                    models.CharField(
                        blank=True, help_text='e.g. "2-3 min"', max_length=30
                    ),
                ),
                (
                    "video_poster",
                    models.ImageField(
                        blank=True,
                        help_text="The still shown before the video plays. Taken from the video automatically; upload your own to replace it.",
                        upload_to="posters/%Y/%m/",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(blank=True, upload_to="book/audio/%Y/%m/"),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True,
                        help_text="Use instead of a file upload for CDN-hosted audio.",
                    ),
                ),
                (
                    "term",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Term 1"), (2, "Term 2"), (3, "Term 3")], default=1
                    ),
                ),
                (
                    "week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Week 1"),
                            (2, "Week 2"),
                            (3, "Week 3"),
                            (4, "Week 4"),
                            (5, "Week 5"),
                            (6, "Week 6"),
                            (7, "Week 7"),
                            (8, "Week 8"),
                            (9, "Week 9"),
                            (10, "Week 10"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                        ],
                        default="monday",
                        max_length=10,
                    ),
                ),
                (
                    "day_order",
                    models.PositiveSmallIntegerField(default=0, editable=False),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='The topic, e.g. "Animals"', max_length=150
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=170)),
                (
                    "target_words",
                    models.TextField(
                        blank=True,
                        help_text="The words this dialogue practises, separated by commas: lion, gorilla, tortoise, giraffe",
                    ),
                ),
                (
                    "script",
                    models.TextField(
                        blank=True,
                        help_text="One line each, as Speaker: words. For example:\nChild: Mummy, is that a lion?\nMummy: No, that's a gorilla.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional tips for the teacher, e.g. how to act it out.",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="For more than one dialogue on the same day.",
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dialogues",
                        to="conversational_dialogue.dialoguelevel",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "level__order",
                    "term",
                    "week",
                    "day_order",
                    "order",
                    "id",
                ],
                "unique_together": {("level", "slug")},
            },
        ),
        migrations.CreateModel(
            name="DialogueProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dialogue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_entries",
                        to="conversational_dialogue.dialogue",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dialogue_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "dialogue progress",
                "unique_together": {("user", "dialogue")},
            },
        ),
    ]
