# Generated by Django 5.2.17 on 2026-09-17 14:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0002_level"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paywall_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to let everyone use every tool for free, e.g. while plans are being set up.",
                    ),
                ),
                (
                    "trial_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Days of free access for a new learner or school. 0 turns the trial off.",
                    ),
                ),
                (
                    "reminder_days",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Start reminding people to renew this many days before their access ends.",
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        blank=True,
                        help_text="Shown on receipts and the plans page for billing questions.",
                        max_length=254,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "billing settings",
                "verbose_name_plural": "billing settings",
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='e.g. "Monthly", "Termly", "Yearly"', max_length=80
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("individual", "Individual learners"),
                            ("school", "Schools"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="One line under the price.",
                        max_length=200,
                    ),
                ),
                (
                    "features",
                    models.TextField(
                        blank=True, help_text="What's included, one per line."
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="In naira, e.g. 5000. Paystack's smallest charge is ₦100.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("100"))
                        ],
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Days of access it buys: 30 for a month, 91 for a term, 365 for a year.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "period_label",
                    models.CharField(
                        blank=True,
                        help_text='Shown after the price, e.g. "per month". Worked out from the days if left blank.',
                        max_length=30,
                    ),
                ),
                (
                    "max_learners",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Schools only: the most teachers and students who can join. Blank for no limit.",
                        null=True,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text='Highlighted as "Most popular".'
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Only active plans can be bought."
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["audience", "order", "price"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "paid_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Paid access runs until this moment.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        help_text="The plan last paid for.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="billing.plan",
                    ),
                ),
                (
                    "school",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="schools.school",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=64, unique=True)),
                ("account_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("plan_name", models.CharField(max_length=80)),
                ("duration_days", models.PositiveIntegerField()),
                ("amount", models.PositiveBigIntegerField(help_text="In kobo.")),
                ("currency", models.CharField(default="NGN", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Paid"),
                            ("failed", "Failed"),
                            ("abandoned", "Not completed"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("channel", models.CharField(blank=True, max_length=30)),
                ("gateway_response", models.CharField(blank=True, max_length=255)),
                ("authorization_url", models.URLField(blank=True, max_length=500)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("period_start", models.DateTimeField(blank=True, null=True)),
                ("period_end", models.DateTimeField(blank=True, null=True)),
                (
                    "raw",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Paystack's last word on this payment.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="billing.plan",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="billing.subscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("school__isnull", True), ("user__isnull", False)),
                    models.Q(("school__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="billing_subscription_one_owner",
            ),
        ),
    ]
