# Generated by Django 5.2.17 on 2026-09-17 14:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_trial_for_existing_accounts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plan",
            options={
                "ordering": [
                    "audience",
                    "min_units",
                    "max_units",
                    "duration_days",
                    "order",
                    "price",
                ]
            },
        ),
        migrations.RemoveField(
            model_name="plan",
            name="max_learners",
        ),
        migrations.AddField(
            model_name="plan",
            name="max_units",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Schools: most teachers this tier allows. Students: most enrolled children in this band — blank for no upper limit (e.g. 500+).",
                null=True,
                verbose_name="up to",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="min_units",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Schools: fewest teachers in this tier. Students: fewest enrolled children in this band. Blank for adults.",
                null=True,
                verbose_name="from",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="audience",
            field=models.CharField(
                choices=[
                    ("individual", "Adults (non-students)"),
                    ("school", "Schools, by number of teachers"),
                    ("student", "Students, per child"),
                ],
                default="individual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="duration_days",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Days of access it buys: 7 a week, 30 a month, 91 a quarter, 122 a term, 365 a year.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Only active plans are shown and can be bought."
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="name",
            field=models.CharField(
                help_text='The period, e.g. "Weekly", "Termly", "Yearly". Plans with the same name share a column in the price tables.',
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="period_label",
            field=models.CharField(
                blank=True,
                help_text='Shown after the price, e.g. "per term". Worked out from the name if left blank.',
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="In naira, e.g. 48000. For students this is the price per child. Paystack's smallest charge is ₦100.",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("100"))],
            ),
        ),
    ]
