# Generated by Django 5.2.17 on 2026-09-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_load_price_sheets"),
    ]

    operations = [
        # Renewal is offered in the last 5 days, not 3.
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model("billing", "BillingSettings").objects.filter(reminder_days=3).update(reminder_days=5),
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="billingsettings",
            name="reminder_days",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Renewal is offered this many days before access ends. People can still renew earlier; the days add on.",
            ),
        ),
    ]
