# Generated by Django 5.2.6 on 2026-09-22 17:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_renew_window"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="discount",
            field=models.PositiveBigIntegerField(
                default=0, help_text="Taken off by a promo code, in kobo."
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="promo_code",
            field=models.CharField(
                blank=True, help_text="The code used, as it was typed.", max_length=20
            ),
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text='What people type, e.g. "JDM201". Leave blank and one is made for you.',
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="For your own records, e.g. “September school fair”. Never shown.",
                        max_length=150,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("percent", "Percentage off"),
                            ("amount", "Naira off"),
                        ],
                        default="percent",
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="How much off: a percentage (e.g. 25 for 25% off), or an amount in naira.",
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="How many accounts may use it. 0 means no limit.",
                    ),
                ),
                (
                    "once_per_account",
                    models.BooleanField(
                        default=True,
                        help_text="An account can use this code only once.",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave blank to start straight away.",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Leave blank for no end date.", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Turn off to stop it working at once."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plans",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The plans it works on. Choose none for every plan.",
                        related_name="promo_codes",
                        to="billing.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "promo code",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromoRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_off",
                    models.PositiveBigIntegerField(default=0, help_text="In kobo."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemption",
                        to="billing.payment",
                    ),
                ),
                (
                    "promo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="billing.promocode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_uses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "promo code use",
                "verbose_name_plural": "promo code uses",
                "ordering": ["-created_at"],
            },
        ),
    ]
