# Generated by Django 5.2.6 on 2026-09-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_promo_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="custom_trial_length",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="custom_trial_set_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="custom_trial_unit",
            field=models.CharField(default="days", max_length=10),
        ),
    ]
