# Generated by Django 5.2.6 on 2026-09-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_learner_trial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="custom_trial_reason",
            field=models.CharField(
                blank=True,
                help_text="Shown to the learner beside their trial days.",
                max_length=120,
            ),
        ),
    ]
