# Generated by Django 5.2.6 on 2026-09-22 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0009_tricks_without_groups"),
        ("tricks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrickActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(blank=True, upload_to="book/videos/%Y/%m/"),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="Use instead of a file upload for CDN-hosted video (e.g. Cloudflare R2, YouTube).",
                    ),
                ),
                ("video_caption", models.CharField(blank=True, max_length=150)),
                (
                    "video_duration_label",
                    models.CharField(
                        blank=True, help_text='e.g. "2-3 min"', max_length=30
                    ),
                ),
                (
                    "video_poster",
                    models.ImageField(
                        blank=True,
                        help_text="The still shown before the video plays. Taken from the video automatically; upload your own to replace it.",
                        upload_to="posters/%Y/%m/",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(blank=True, upload_to="book/audio/%Y/%m/"),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True,
                        help_text="Use instead of a file upload for CDN-hosted audio.",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("transcription", "🔤  Transcription — Typed answer"),
                            ("dictation", "🎧  Spelling dictation — Typed answer"),
                            ("missing-letters", "✏️  Missing letters — Typed answer"),
                            (
                                "word-scramble",
                                "🧩  Puzzle — word scramble — Typed answer",
                            ),
                            ("syllable-count", "🔢  Syllable count — Typed answer"),
                            ("spelling-fix", "🩹  Correct the spelling — Typed answer"),
                            (
                                "word-to-sentence",
                                "📝  Use it in a sentence — Typed answer",
                            ),
                            (
                                "listen-choose",
                                "🎧  Listen and choose — Multiple choice",
                            ),
                            ("minimal-pairs", "👂  Minimal pairs — Multiple choice"),
                            ("odd-one-out", "🔍  Odd one out — Multiple choice"),
                            ("stress-placement", "📈  Word stress — Multiple choice"),
                            ("silent-letter", "🤫  Silent letters — Multiple choice"),
                            ("homophones", "👯  Homophones — Multiple choice"),
                            ("rhyme-match", "🎵  Rhyme match — Multiple choice"),
                            (
                                "sound-to-symbol",
                                "🔣  Sound to symbol — Multiple choice",
                            ),
                            ("picture-word", "🖼️  Picture and word — Multiple choice"),
                            ("sound-sort", "🗂️  Sound sort — Drag into boxes"),
                            (
                                "sentence-builder",
                                "🧱  Sentence builder — Drag into order",
                            ),
                            (
                                "listen-and-number",
                                "🧮  Listen and number — Drag into order",
                            ),
                            ("read-aloud", "🎙️  Read aloud — Record your voice"),
                            (
                                "repeat-after",
                                "🔁  Listen and repeat — Record your voice",
                            ),
                            (
                                "tongue-twister",
                                "🌀  Tongue twister — Record your voice",
                            ),
                        ],
                        default="transcription",
                        help_text="What learners do, and how their answers get marked.",
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("slug", models.SlugField(blank=True, max_length=160)),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Shown above the questions. Leave blank to use this kind's standard wording.",
                    ),
                ),
                (
                    "buckets",
                    models.TextField(
                        blank=True,
                        help_text="Only for Sound sort — the boxes to drag words into, one per line, e.g.:\n/iː/ as in sheep\n/ɪ/ as in ship",
                        verbose_name="sorting boxes",
                    ),
                ),
                (
                    "pass_mark",
                    models.PositiveIntegerField(
                        default=70, help_text="Percentage needed to pass, e.g. 70"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "trick",
                    models.ForeignKey(
                        help_text="The trick this activity tests. Passing all of a trick's activities unlocks the next trick.",
                        limit_choices_to={"category__programme": "tricks"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trick_activities",
                        to="book.sound",
                    ),
                ),
            ],
            options={
                "verbose_name": "trick activity",
                "verbose_name_plural": "trick activities",
                "ordering": ["trick", "order", "id"],
                "unique_together": {("trick", "slug")},
            },
        ),
        migrations.CreateModel(
            name="TrickActivityAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0)),
                ("max_score", models.PositiveIntegerField(default=0)),
                ("percent", models.PositiveIntegerField(default=0)),
                ("passed", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("marked", "Marked automatically"),
                            ("awaiting", "Waiting for the teacher"),
                            ("reviewed", "Reviewed by the teacher"),
                        ],
                        default="marked",
                        max_length=20,
                    ),
                ),
                ("teacher_feedback", models.TextField(blank=True)),
                (
                    "teacher_score",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Out of 100, for recorded activities.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="tricks.trickactivity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trick_activity_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "trick activity attempt",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrickActivityItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(blank=True, upload_to="book/audio/%Y/%m/"),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True,
                        help_text="Use instead of a file upload for CDN-hosted audio.",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        blank=True, help_text="What the learner is shown."
                    ),
                ),
                (
                    "answer",
                    models.TextField(
                        blank=True,
                        help_text="The correct answer. Separate equally correct answers with a vertical bar, e.g. colour|color",
                    ),
                ),
                (
                    "options",
                    models.TextField(
                        blank=True,
                        help_text="For multiple choice — the options, one per line.",
                    ),
                ),
                ("hint", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="tricks/activities/%Y/%m/"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="tricks.trickactivity",
                    ),
                ),
            ],
            options={
                "verbose_name": "activity question",
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrickActivityResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("given", models.TextField(blank=True)),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                (
                    "recording",
                    models.FileField(blank=True, upload_to="tricks/recordings/%Y/%m/"),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="tricks.trickactivityattempt",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="tricks.trickactivityitem",
                    ),
                ),
            ],
            options={
                "ordering": ["item__order", "id"],
            },
        ),
    ]
