# Generated by Django 5.2.6 on 2026-09-22 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0009_tricks_without_groups"),
        ("tricks", "0003_lessons_in_both_programmes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lessonactivity",
            options={
                "ordering": ["lesson", "order", "id"],
                "verbose_name": "assessment activity",
                "verbose_name_plural": "assessment activities",
            },
        ),
        migrations.AlterModelOptions(
            name="lessonactivityattempt",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "assessment activity attempt",
            },
        ),
        migrations.AlterModelOptions(
            name="lessonprogress",
            options={
                "verbose_name": "lesson progress",
                "verbose_name_plural": "lesson progress",
            },
        ),
        migrations.AlterField(
            model_name="lessonactivity",
            name="lesson",
            field=models.ForeignKey(
                help_text="The sound or trick this activity tests. Passing all of a lesson's activities unlocks the next one.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_activities",
                to="book.sound",
            ),
        ),
        migrations.AlterField(
            model_name="lessonactivityattempt",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_activity_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="lessonprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
