# Generated by Django 5.2.6 on 2026-09-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tricks", "0004_lesson_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonactivityattempt",
            name="teacher_audio_feedback",
            field=models.FileField(
                blank=True,
                help_text="Audio feedback recorded by the teacher.",
                upload_to="teacher-feedback/%Y/%m/",
            ),
        ),
    ]
