# Generated by Django 5.2.6 on 2026-09-26 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text='e.g. "Days & Months"', max_length=100),
                ),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="One line shown on the Assembly Recitals page.",
                        max_length=255,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="📣",
                        help_text="An emoji for the section's card, e.g. 📅",
                        max_length=8,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Unpublished sections are hidden from learners.",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Recital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(blank=True, upload_to="book/videos/%Y/%m/"),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="Use instead of a file upload for CDN-hosted video (e.g. Cloudflare R2, YouTube).",
                    ),
                ),
                ("video_caption", models.CharField(blank=True, max_length=150)),
                (
                    "video_duration_label",
                    models.CharField(
                        blank=True, help_text='e.g. "2-3 min"', max_length=30
                    ),
                ),
                (
                    "video_poster",
                    models.ImageField(
                        blank=True,
                        help_text="The still shown before the video plays. Taken from the video automatically; upload your own to replace it.",
                        upload_to="posters/%Y/%m/",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(blank=True, upload_to="book/audio/%Y/%m/"),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True,
                        help_text="Use instead of a file upload for CDN-hosted audio.",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='e.g. "Days of the Week"', max_length=150
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=170)),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="One line shown in the section's list.",
                        max_length=255,
                    ),
                ),
                (
                    "lines",
                    models.TextField(
                        blank=True,
                        help_text="The words, one line per line, exactly as they are recited or sung. Leave a blank line between verses.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes for the teacher leading it, e.g. actions or how to split the hall.",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recitals",
                        to="assembly_recitals.section",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "title"],
                "unique_together": {("section", "slug")},
            },
        ),
    ]
