# Generated by Django 5.2.17 on 2026-09-17 11:47

import apps.landing.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteBranding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="PNG with a transparent background works best. Shown about 40px tall. Up to 2 MB.",
                        upload_to="branding/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg", "webp"]
                            ),
                            apps.landing.models.validate_logo_size,
                        ],
                    ),
                ),
                (
                    "show_name_with_logo",
                    models.BooleanField(
                        default=True,
                        help_text="Untick if the logo already spells out “Diction Masters”, so the name isn't shown twice.",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="The small icon in the browser tab. A square PNG, at least 48×48 (512×512 is ideal), or an .ico file. Up to 500 KB.",
                        upload_to="branding/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "ico"]
                            ),
                            apps.landing.models.validate_favicon_size,
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "logo & favicon",
                "verbose_name_plural": "logo & favicon",
            },
        ),
    ]
