# Generated by Django 5.2.6 on 2026-09-23 19:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0002_level"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("book", "Book"),
                            ("story", "Story"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                            ("other", "Other resource"),
                        ],
                        default="book",
                        max_length=12,
                    ),
                ),
                ("summary", models.CharField(blank=True, max_length=300)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional text or story content."
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Books, documents, audio, video or cover image.",
                        upload_to="diction_library/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                [
                                    "pdf",
                                    "epub",
                                    "doc",
                                    "docx",
                                    "txt",
                                    "mp3",
                                    "m4a",
                                    "wav",
                                    "ogg",
                                    "mp4",
                                    "webm",
                                    "mov",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "webp",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional link to hosted audio, video or a resource.",
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="library_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for content shared with every user. Select a school to limit access to its members.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="library_items",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diction Library item",
                "verbose_name_plural": "Diction Library items",
                "ordering": ["-created_at", "title"],
            },
        ),
    ]
