# Generated by Django 5.2.6 on 2026-09-29 10:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diction_library", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryitem",
            name="narration_chars",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="libraryitem",
            name="narration_file",
            field=models.FileField(
                blank=True,
                help_text="Your own recording of the book read aloud. Leave empty and one is made automatically from the book's text, starting where the story starts (the contents pages are skipped).",
                upload_to="diction_library/narration/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["mp3", "m4a", "wav", "ogg"]
                    )
                ],
                verbose_name="Narration (optional)",
            ),
        ),
        migrations.AddField(
            model_name="libraryitem",
            name="narration_note",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name="libraryitem",
            name="narration_redo",
            field=models.BooleanField(
                default=False,
                help_text="Tick and save to make the read-aloud audio again from the current file (it uses voice credits).",
                verbose_name="Make the read-aloud again",
            ),
        ),
        migrations.AddField(
            model_name="libraryitem",
            name="narration_source",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="libraryitem",
            name="narration_status",
            field=models.CharField(blank=True, editable=False, max_length=12),
        ),
        migrations.CreateModel(
            name="LibraryChapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "text",
                    models.TextField(
                        help_text="The words read aloud, paragraphs separated by a blank line."
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True, upload_to="diction_library/narration/%Y/%m/"
                    ),
                ),
                ("audio_url", models.URLField(blank=True)),
                ("generated", models.BooleanField(default=False)),
                ("source_hash", models.CharField(blank=True, max_length=64)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="diction_library.libraryitem",
                    ),
                ),
            ],
            options={
                "ordering": ["item", "order"],
            },
        ),
    ]
