# Generated by Django 5.2.6 on 2026-09-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diction_library", "0002_narration"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryitem",
            name="narration_owner",
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name="libraryitem",
            name="narration_updated",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name="librarychapter",
            constraint=models.UniqueConstraint(
                fields=("item", "order"), name="one_chapter_per_place"
            ),
        ),
    ]
