# Generated by Django 5.2.6 on 2026-10-03 10:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def single_recording_into_many(apps, schema_editor):
    """A book's one uploaded narration becomes its first recording."""
    LibraryItem = apps.get_model("diction_library", "LibraryItem")
    LibraryRecording = apps.get_model("diction_library", "LibraryRecording")
    for item in LibraryItem.objects.exclude(narration_file=""):
        LibraryRecording.objects.create(item=item, name=item.title[:200] or "Narration", audio_file=item.narration_file.name)
        LibraryItem.objects.filter(pk=item.pk).update(narration_file="")


class Migration(migrations.Migration):

    dependencies = [
        ("diction_library", "0003_narration_claim"),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='What it is, e.g. "Chapter five" or "Page 121 to 124".',
                        max_length=200,
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        upload_to="diction_library/narration/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["mp3", "m4a", "wav", "ogg", "aac"]
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to="diction_library.libraryitem",
                    ),
                ),
            ],
            options={
                "ordering": ["item", "name"],
            },
        ),
        migrations.RunPython(single_recording_into_many, migrations.RunPython.noop),
    ]
