# Generated by Django 5.2.6 on 2026-10-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diction_library", "0004_many_recordings"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryitem",
            name="levels",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The levels this is for. Leave every box empty for every level.",
                max_length=255,
            ),
        ),
    ]
