# Generated by Django 5.2.17 on 2026-09-15 14:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("slug", models.SlugField(blank=True, max_length=170, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("practice", "Practice quiz"),
                            ("timed", "Timed test"),
                            ("speaking", "Speaking assessment"),
                            ("placement", "Placement test"),
                        ],
                        default="practice",
                        max_length=20,
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="One line shown in the list.",
                        max_length=255,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True, help_text="Shown before the learner starts."
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pre-Level", "Pre-Level"),
                            ("Level 1", "Level 1"),
                            ("Level 2", "Level 2"),
                            ("Level 3", "Level 3"),
                            ("Level 4", "Level 4"),
                            ("Level 5", "Level 5"),
                            ("Level 6", "Level 6"),
                            ("Level 7", "Level 7"),
                            ("Level 8", "Level 8"),
                            ("Level 9", "Level 9"),
                            ("Level 10", "Level 10"),
                            ("Level 11", "Level 11"),
                            ("Level 12", "Level 12"),
                        ],
                        help_text="The level this is aimed at. Leave blank for a placement test.",
                        max_length=100,
                    ),
                ),
                (
                    "time_limit_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Required for a timed test; optional for a placement test.",
                        null=True,
                    ),
                ),
                (
                    "pass_mark",
                    models.PositiveIntegerField(
                        default=70, help_text="Percentage needed to pass."
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="How many times a learner may sit it. 0 means no limit.",
                    ),
                ),
                (
                    "shuffle_questions",
                    models.BooleanField(
                        default=True,
                        help_text="Give each attempt its own question order.",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["kind", "order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("submitted", "Marked automatically"),
                            ("awaiting", "Waiting for marking"),
                            ("marked", "Marked by a teacher"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("question_order", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("deadline_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=7
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=7
                    ),
                ),
                ("percent", models.PositiveSmallIntegerField(default=0)),
                ("passed", models.BooleanField(default=False)),
                ("grade", models.CharField(blank=True, max_length=30)),
                ("recommended_level", models.CharField(blank=True, max_length=100)),
                ("marked_at", models.DateTimeField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="assessments.assessment",
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(blank=True, upload_to="book/audio/%Y/%m/"),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True,
                        help_text="Use instead of a file upload for CDN-hosted audio.",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("choice", "Multiple choice"),
                            ("listen", "Listen and choose"),
                            ("transcribe", "Type the transcription"),
                            ("spell", "Type the word"),
                            ("speak", "Speak and record"),
                        ],
                        default="choice",
                        max_length=20,
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        help_text="The question, e.g. Which is the correct transcription of CHURCH?"
                    ),
                ),
                (
                    "word",
                    models.CharField(
                        blank=True,
                        help_text="Optional word shown large with the question, e.g. THINK.",
                        max_length=100,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="assessments/images/%Y/%m/"
                    ),
                ),
                (
                    "options",
                    models.TextField(
                        blank=True,
                        help_text="For multiple choice and listening questions — one option per line.",
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        blank=True,
                        help_text="The correct answer. For multiple choice it must match an option exactly. Separate equally correct answers with |",
                        max_length=255,
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Why that's the answer — shown once they've answered.",
                    ),
                ),
                ("points", models.PositiveIntegerField(default=1)),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pre-Level", "Pre-Level"),
                            ("Level 1", "Level 1"),
                            ("Level 2", "Level 2"),
                            ("Level 3", "Level 3"),
                            ("Level 4", "Level 4"),
                            ("Level 5", "Level 5"),
                            ("Level 6", "Level 6"),
                            ("Level 7", "Level 7"),
                            ("Level 8", "Level 8"),
                            ("Level 9", "Level 9"),
                            ("Level 10", "Level 10"),
                            ("Level 11", "Level 11"),
                            ("Level 12", "Level 12"),
                        ],
                        help_text="For placement tests: the level this question checks.",
                        max_length=100,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="assessments.assessment",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("given", models.TextField(blank=True)),
                (
                    "recording",
                    models.FileField(
                        blank=True, upload_to="assessments/recordings/%Y/%m/"
                    ),
                ),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                (
                    "points_awarded",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sound",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                    ),
                ),
                (
                    "stress",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                    ),
                ),
                (
                    "articulation",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                    ),
                ),
                (
                    "pace",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                    ),
                ),
                (
                    "rhythm",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="assessments.attempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="assessments.question",
                    ),
                ),
            ],
            options={
                "unique_together": {("attempt", "question")},
            },
        ),
    ]
