# Generated by Django 5.2.6 on 2026-09-22 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
        ("book", "0009_tricks_without_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="trick",
            field=models.OneToOneField(
                blank=True,
                help_text="The trick this assessment belongs to. Passing it unlocks the next trick.",
                limit_choices_to={"category__programme": "tricks"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trick_assessment",
                to="book.sound",
            ),
        ),
    ]
