# Generated by Django 5.2.6 on 2026-09-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_assessment_trick"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessment",
            name="trick",
        ),
    ]
