# Generated by Django 5.2.6 on 2026-09-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0003_remove_assessment_trick"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="teacher_audio_feedback",
            field=models.FileField(blank=True, upload_to="teacher-feedback/%Y/%m/"),
        ),
    ]
