# Generated by Django 5.2.6 on 2026-10-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0004_attempt_teacher_audio_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="ca_number",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "CA 1"), (2, "CA 2")],
                help_text="CA tests: the first or the second of the term.",
                null=True,
                verbose_name="CA number",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="closes_at",
            field=models.DateTimeField(
                blank=True, help_text="CA tests and exams: when it shuts.", null=True
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="opens_at",
            field=models.DateTimeField(
                blank=True,
                help_text="CA tests and exams: when it can be started.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="term",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "First Term"), (2, "Second Term"), (3, "Third Term")],
                help_text="CA tests and exams: the term it counts towards.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="kind",
            field=models.CharField(
                choices=[
                    ("practice", "Practice quiz"),
                    ("timed", "Timed test"),
                    ("speaking", "Speaking assessment"),
                    ("placement", "Placement test"),
                    ("ca", "CA test"),
                    ("exam", "Exam"),
                ],
                default="practice",
                max_length=20,
            ),
        ),
    ]
