# Generated by Django 5.2.17 on 2026-09-14 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_name",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, editable=False)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="LearningModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(blank=True, max_length=170, unique=True)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="One or two sentences shown on the Learning Modules hub.",
                        max_length=255,
                    ),
                ),
                (
                    "overview",
                    models.TextField(
                        blank=True,
                        help_text="A longer introduction shown on the module's own page.",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="📚",
                        help_text="A single emoji shown on the module's badge, e.g. 🔍 📚 🎤 🏆",
                        max_length=8,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#1B3A6B",
                        help_text='Badge colour as a hex code, e.g. "#7C3AED"',
                        max_length=7,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Unpublished modules are hidden from the hub.",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="LessonItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(blank=True, upload_to="book/videos/%Y/%m/"),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="Use instead of a file upload for CDN-hosted video (e.g. Cloudflare R2, YouTube).",
                    ),
                ),
                ("video_caption", models.CharField(blank=True, max_length=150)),
                (
                    "video_duration_label",
                    models.CharField(
                        blank=True, help_text='e.g. "2-3 min"', max_length=30
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(blank=True, upload_to="book/audio/%Y/%m/"),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True,
                        help_text="Use instead of a file upload for CDN-hosted audio.",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='e.g. "Sound Introduction"', max_length=150
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="One line shown under the title, e.g. what this activity covers.",
                        max_length=255,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes or a transcript shown below the player.",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_items",
                        to="learning_modules.day",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="LessonResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "file",
                    models.FileField(
                        blank=True, upload_to="learning_modules/resources/%Y/%m/"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Use instead of a file upload for an externally hosted resource.",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "lesson_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="learning_modules.lessonitem",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text='e.g. "First Term"', max_length=100),
                ),
                ("slug", models.SlugField(blank=True, max_length=120)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="learning_modules.learningmodule",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("module", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Week",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="Week number within the term, e.g. 1"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text='Optional, e.g. "Revision Week"',
                        max_length=150,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=120)),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weeks",
                        to="learning_modules.term",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
                "unique_together": {("term", "number")},
            },
        ),
        migrations.AddField(
            model_name="day",
            name="week",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="learning_modules.week",
            ),
        ),
        migrations.CreateModel(
            name="DayProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_entries",
                        to="learning_modules.day",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Day progress",
                "unique_together": {("user", "day")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="day",
            unique_together={("week", "day_name")},
        ),
    ]
