# Generated by Django 5.2.17 on 2026-09-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_modules", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningmodule",
            name="color",
            field=models.CharField(
                choices=[
                    ("#14213D", "Ink navy"),
                    ("#7A2438", "Maroon"),
                    ("#B8863B", "Gold"),
                    ("#24473E", "Green"),
                    ("#0B5E5E", "Teal"),
                    ("#1F6F8B", "Ocean blue"),
                    ("#7C3AED", "Purple"),
                    ("#8E44AD", "Violet"),
                    ("#9D174D", "Rose"),
                    ("#B03A2E", "Rust"),
                    ("#C2410C", "Amber"),
                    ("#374151", "Slate"),
                ],
                default="#14213D",
                help_text="Badge colour.",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="learningmodule",
            name="icon",
            field=models.CharField(
                choices=[
                    ("📚", "📚 Books"),
                    ("📖", "📖 Open book"),
                    ("🔍", "🔍 Magnifying glass"),
                    ("🎤", "🎤 Microphone"),
                    ("🎧", "🎧 Headphones"),
                    ("🗣️", "🗣️ Speaking head"),
                    ("💬", "💬 Speech bubble"),
                    ("✍️", "✍️ Writing hand"),
                    ("📝", "📝 Notes"),
                    ("🔤", "🔤 Letters"),
                    ("🧠", "🧠 Brain"),
                    ("🎯", "🎯 Target"),
                    ("🎭", "🎭 Theatre masks"),
                    ("🎨", "🎨 Palette"),
                    ("🎵", "🎵 Musical note"),
                    ("🧩", "🧩 Puzzle piece"),
                    ("🔬", "🔬 Microscope"),
                    ("🧭", "🧭 Compass"),
                    ("🧮", "🧮 Abacus"),
                    ("🗓️", "🗓️ Calendar"),
                    ("⭐", "⭐ Star"),
                    ("🌟", "🌟 Glowing star"),
                    ("🏆", "🏆 Trophy"),
                    ("🏅", "🏅 Medal"),
                    ("🎓", "🎓 Graduation cap"),
                    ("📣", "📣 Megaphone"),
                    ("🚀", "🚀 Rocket"),
                    ("🌍", "🌍 Globe"),
                ],
                default="📚",
                help_text="Shown on the module's badge.",
                max_length=8,
            ),
        ),
    ]
