# Generated by Django 5.2.17 on 2026-09-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "learning_modules",
            "0002_alter_learningmodule_color_alter_learningmodule_icon",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonitem",
            name="video_poster",
            field=models.ImageField(
                blank=True,
                help_text="The still shown before the video plays. Taken from the video automatically; upload your own to replace it.",
                upload_to="posters/%Y/%m/",
            ),
        ),
    ]
