# Generated by Django 5.2.6 on 2026-10-03 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_modules", "0003_video_poster"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="learning_modules/slides/%Y/%m/"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text='Shown under the picture, e.g. "A big red apple".',
                        max_length=200,
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        help_text="Optional: a recording that plays when this slide opens, e.g. the word being said.",
                        upload_to="learning_modules/slides/audio/%Y/%m/",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "lesson_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slides",
                        to="learning_modules.lessonitem",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
