# Generated by Django 5.2.6 on 2026-10-08 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_modules", "0004_lesson_slides"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DayItemsSeen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "items_seen",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="LessonItem ids opened, in the order first opened.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="learning_modules.day",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_items_seen",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "day items seen",
                "verbose_name_plural": "day items seen",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "day"), name="one_items_seen_per_day"
                    )
                ],
            },
        ),
    ]
