# Generated by Django 5.2.17 on 2026-09-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quick_words", "0002_seed_words"),
    ]

    operations = [
        migrations.AddField(
            model_name="quickword",
            name="source",
            field=models.CharField(
                choices=[("staff", "Added by staff"), ("ai", "Looked up by AI")],
                default="staff",
                max_length=10,
            ),
        ),
    ]
