# Generated by Django 5.2.6 on 2026-09-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quick_words", "0003_word_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="quickword",
            name="synonyms",
            field=models.CharField(
                blank=True,
                help_text='Comma-separated everyday synonyms, e.g. "happy, glad, pleased".',
                max_length=200,
            ),
        ),
    ]
