# Generated by Django 5.2.6 on 2026-10-08 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessments", "0005_assessment_ca_number_assessment_closes_at_and_more"),
        ("echospell", "0020_groupstepsseen"),
        ("learning_modules", "0006_learningmodule_levels"),
        ("schools", "0007_level_changes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Grading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ca1_weight",
                    models.PositiveSmallIntegerField(
                        default=20, verbose_name="CA 1 counts for (%)"
                    ),
                ),
                (
                    "ca2_weight",
                    models.PositiveSmallIntegerField(
                        default=20, verbose_name="CA 2 counts for (%)"
                    ),
                ),
                (
                    "exam_weight",
                    models.PositiveSmallIntegerField(
                        default=60, verbose_name="Exam counts for (%)"
                    ),
                ),
                (
                    "a_from",
                    models.PositiveSmallIntegerField(default=70, verbose_name="A from"),
                ),
                (
                    "b_from",
                    models.PositiveSmallIntegerField(default=60, verbose_name="B from"),
                ),
                (
                    "c_from",
                    models.PositiveSmallIntegerField(default=50, verbose_name="C from"),
                ),
                (
                    "d_from",
                    models.PositiveSmallIntegerField(default=45, verbose_name="D from"),
                ),
                (
                    "e_from",
                    models.PositiveSmallIntegerField(default=40, verbose_name="E from"),
                ),
                (
                    "pass_mark",
                    models.PositiveSmallIntegerField(
                        default=50,
                        help_text="A session average from this mark is suggested for promotion.",
                        verbose_name="Promote from (%)",
                    ),
                ),
            ],
            options={
                "verbose_name": "grading",
                "verbose_name_plural": "grading",
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='The school year, e.g. "2026/2027".',
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "school year",
                "ordering": ["-name"],
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starts", models.DateField()),
                ("ends", models.DateField()),
                (
                    "break_starts",
                    models.DateField(
                        blank=True, null=True, verbose_name="Mid-term break starts"
                    ),
                ),
                (
                    "break_ends",
                    models.DateField(
                        blank=True, null=True, verbose_name="Mid-term break ends"
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "First Term"),
                            (2, "Second Term"),
                            (3, "Third Term"),
                        ]
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="scheme.session",
                    ),
                ),
            ],
            options={
                "ordering": ["starts"],
            },
        ),
        migrations.CreateModel(
            name="SchoolTermDates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starts", models.DateField()),
                ("ends", models.DateField()),
                (
                    "break_starts",
                    models.DateField(
                        blank=True, null=True, verbose_name="Mid-term break starts"
                    ),
                ),
                (
                    "break_ends",
                    models.DateField(
                        blank=True, null=True, verbose_name="Mid-term break ends"
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_dates",
                        to="schools.school",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_dates",
                        to="scheme.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "school term dates",
                "verbose_name_plural": "school term dates",
            },
        ),
        migrations.CreateModel(
            name="ReportCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(blank=True, max_length=100)),
                ("ca1", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("ca2", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("exam", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("total", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("grade", models.CharField(blank=True, max_length=2)),
                ("days_practised", models.PositiveSmallIntegerField(default=0)),
                ("teacher_comment", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "comment_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_cards",
                        to="scheme.term",
                    ),
                ),
            ],
            options={
                "ordering": ["-term__starts"],
            },
        ),
        migrations.CreateModel(
            name="SchemeWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Pre-Level", "Pre-Level"),
                            ("Level 1", "Level 1"),
                            ("Level 2", "Level 2"),
                            ("Level 3", "Level 3"),
                            ("Level 4", "Level 4"),
                            ("Level 5", "Level 5"),
                            ("Level 6", "Level 6"),
                            ("Level 7", "Level 7"),
                            ("Level 8", "Level 8"),
                            ("Level 9", "Level 9"),
                            ("Level 10", "Level 10"),
                            ("Level 11", "Level 11"),
                            ("Level 12", "Level 12"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "term",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "First Term"),
                            (2, "Second Term"),
                            (3, "Third Term"),
                        ]
                    ),
                ),
                (
                    "week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Week 1"),
                            (2, "Week 2"),
                            (3, "Week 3"),
                            (4, "Week 4"),
                            (5, "Week 5"),
                            (6, "Week 6"),
                            (7, "Week 7"),
                            (8, "Week 8"),
                            (9, "Week 9"),
                            (10, "Week 10"),
                            (11, "Week 11"),
                            (12, "Week 12"),
                            (13, "Week 13"),
                            (14, "Week 14"),
                        ]
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='The week\'s topic, e.g. "The /θ/ and /ð/ sounds".',
                        max_length=150,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Short notes for the teacher: what to teach and how.",
                    ),
                ),
                (
                    "dialogue_week",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Week 1"),
                            (2, "Week 2"),
                            (3, "Week 3"),
                            (4, "Week 4"),
                            (5, "Week 5"),
                            (6, "Week 6"),
                            (7, "Week 7"),
                            (8, "Week 8"),
                            (9, "Week 9"),
                            (10, "Week 10"),
                            (11, "Week 11"),
                            (12, "Week 12"),
                            (13, "Week 13"),
                            (14, "Week 14"),
                        ],
                        help_text="The Conversational Dialogue week for this level and term.",
                        null=True,
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        blank=True,
                        help_text="A test this week, e.g. a CA test.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheme_weeks",
                        to="assessments.assessment",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="EchoSpell groups for this week, in the order to do them.",
                        related_name="scheme_weeks",
                        to="echospell.group",
                    ),
                ),
                (
                    "module_week",
                    models.ForeignKey(
                        blank=True,
                        help_text="A Learning Modules week to work through.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheme_weeks",
                        to="learning_modules.week",
                    ),
                ),
            ],
            options={
                "verbose_name": "scheme of work week",
                "ordering": ["level", "term", "week"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("level", "term", "week"), name="one_scheme_week"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="term",
            constraint=models.UniqueConstraint(
                fields=("session", "number"), name="one_term_number_per_session"
            ),
        ),
        migrations.AddConstraint(
            model_name="schooltermdates",
            constraint=models.UniqueConstraint(
                fields=("school", "term"), name="one_dates_per_school_term"
            ),
        ),
        migrations.AddConstraint(
            model_name="reportcard",
            constraint=models.UniqueConstraint(
                fields=("student", "term"), name="one_report_card_per_term"
            ),
        ),
    ]
