# Generated by Django 5.2.6 on 2026-10-08 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assembly_recitals", "0002_starter_sections"),
        ("assessments", "0005_assessment_ca_number_assessment_closes_at_and_more"),
        ("book", "0011_sound_card_image"),
        ("conversational_dialogue", "0002_levels_and_first_dialogue"),
        ("diction_library", "0005_libraryitem_levels"),
        ("echospell", "0020_groupstepsseen"),
        ("learning_modules", "0006_learningmodule_levels"),
        ("reading_club", "0003_book_levels"),
        ("scheme", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SchemeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Pre-Level", "Pre-Level"),
                            ("Level 1", "Level 1"),
                            ("Level 2", "Level 2"),
                            ("Level 3", "Level 3"),
                            ("Level 4", "Level 4"),
                            ("Level 5", "Level 5"),
                            ("Level 6", "Level 6"),
                            ("Level 7", "Level 7"),
                            ("Level 8", "Level 8"),
                            ("Level 9", "Level 9"),
                            ("Level 10", "Level 10"),
                            ("Level 11", "Level 11"),
                            ("Level 12", "Level 12"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "term",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "First Term"),
                            (2, "Second Term"),
                            (3, "Third Term"),
                        ]
                    ),
                ),
                (
                    "week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Week 1"),
                            (2, "Week 2"),
                            (3, "Week 3"),
                            (4, "Week 4"),
                            (5, "Week 5"),
                            (6, "Week 6"),
                            (7, "Week 7"),
                            (8, "Week 8"),
                            (9, "Week 9"),
                            (10, "Week 10"),
                            (11, "Week 11"),
                            (12, "Week 12"),
                            (13, "Week 13"),
                            (14, "Week 14"),
                        ]
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Any day this week"),
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("group", "EchoSpell group"),
                            ("module_day", "Learning Modules day"),
                            ("dialogue", "Conversational Dialogue"),
                            ("sound", "44 Academy sound"),
                            ("trick", "Tricks to Sound Fluent lesson"),
                            ("chapter", "Reading Club chapter"),
                            ("recital", "Assembly Recital"),
                            ("library", "Diction Library item"),
                            ("assessment", "Assessment"),
                            ("daily_practice", "Daily Practice"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="assessments.assessment",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="reading_club.chapter",
                    ),
                ),
                (
                    "dialogue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="conversational_dialogue.dialogue",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="echospell.group",
                    ),
                ),
                (
                    "library_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="diction_library.libraryitem",
                    ),
                ),
                (
                    "module_day",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="learning_modules.day",
                    ),
                ),
                (
                    "recital",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="assembly_recitals.recital",
                    ),
                ),
                (
                    "sound",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="book.sound",
                    ),
                ),
            ],
            options={
                "verbose_name": "scheme of work entry",
                "verbose_name_plural": "scheme of work entries",
                "ordering": ["level", "term", "week", "day", "order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="SchemeOpened",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opened",
                        to="scheme.schemeentry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheme_opened",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="SchemeWeek",
        ),
        migrations.AddIndex(
            model_name="schemeentry",
            index=models.Index(
                fields=["level", "term", "week"], name="scheme_sche_level_1477c2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="schemeopened",
            constraint=models.UniqueConstraint(
                fields=("user", "entry"), name="one_opened_per_entry"
            ),
        ),
    ]
