# Generated by Django 5.2.6 on 2026-10-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assembly_recitals", "0002_starter_sections"),
        ("assessments", "0005_assessment_ca_number_assessment_closes_at_and_more"),
        ("book", "0011_sound_card_image"),
        ("conversational_dialogue", "0002_levels_and_first_dialogue"),
        ("diction_library", "0005_libraryitem_levels"),
        ("echospell", "0020_groupstepsseen"),
        ("learning_modules", "0006_learningmodule_levels"),
        ("reading_club", "0003_book_levels"),
        ("scheme", "0002_schemeentry_schemeopened_delete_schemeweek_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schemeentry",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="schemeentry",
            index=models.Index(
                fields=["level", "term", "is_draft"],
                name="scheme_sche_level_9c98c5_idx",
            ),
        ),
    ]
