# Generated by Django 5.2.6 on 2026-10-09 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("echospell", "0020_groupstepsseen"),
        ("scheme", "0004_scheme_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="schemeentry",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="echospell.activity",
            ),
        ),
        migrations.AddField(
            model_name="schemeentry",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="echospell.category",
            ),
        ),
        migrations.AlterField(
            model_name="schemeentry",
            name="kind",
            field=models.CharField(
                choices=[
                    ("card", "EchoSpell card"),
                    ("activity", "EchoSpell activity"),
                    ("group", "EchoSpell group"),
                    ("module_day", "Learning Modules day"),
                    ("dialogue", "Conversational Dialogue"),
                    ("sound", "44 Academy sound"),
                    ("trick", "Tricks to Sound Fluent lesson"),
                    ("chapter", "Reading Club chapter"),
                    ("recital", "Assembly Recital"),
                    ("library", "Diction Library item"),
                    ("assessment", "Assessment"),
                    ("daily_practice", "Daily Practice"),
                ],
                max_length=20,
            ),
        ),
    ]
