# Generated by Django 5.2.17 on 2026-09-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesscode",
            name="level",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
