# Generated by Django 5.2.6 on 2026-09-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="max_students",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="How many students this school may register. Leave blank for no limit.",
                null=True,
                verbose_name="Students allowed",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="max_teachers",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="How many teachers this school may register. Leave blank for no limit.",
                null=True,
                verbose_name="Teachers allowed",
            ),
        ),
    ]
