# Generated by Django 5.2.6 on 2026-09-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0003_seat_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="trial_length",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="school",
            name="trial_set_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="school",
            name="trial_unit",
            field=models.CharField(
                choices=[("days", "days"), ("weeks", "weeks"), ("months", "months")],
                default="days",
                max_length=10,
            ),
        ),
    ]
