# Generated by Django 5.2.6 on 2026-09-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0004_school_trial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="trial_reason",
            field=models.CharField(
                blank=True,
                help_text="Shown to the school beside its trial days.",
                max_length=120,
            ),
        ),
    ]
