# Generated by Django 5.2.6 on 2026-10-03 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0007_level_changes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "audio_file",
                    models.FileField(blank=True, upload_to="scan_listen/%Y/%m/"),
                ),
                ("audio_text", models.TextField(blank=True)),
                (
                    "audio_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("audio_duration", models.FloatField(blank=True, null=True)),
                (
                    "audio_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "No audio"),
                            ("working", "Making audio"),
                            ("ready", "Audio ready"),
                            ("failed", "Failed"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("audio_error", models.CharField(blank=True, max_length=300)),
                ("audio_updated", models.DateTimeField(blank=True, null=True)),
                ("plays", models.PositiveIntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_readings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_readings",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
