# Generated by Django 5.2.6 on 2026-10-08 15:26

import apps.learning_tools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_tools", "0001_scan_readings"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolLevels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tool",
                    models.CharField(
                        choices=apps.learning_tools.models._tool_choices,
                        max_length=60,
                        unique=True,
                    ),
                ),
                (
                    "levels",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The levels whose students may open this tool. Leave every box empty for every level.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "tool levels",
                "verbose_name_plural": "tool levels",
                "ordering": ["tool"],
            },
        ),
    ]
