# Generated by Django 5.2.6 on 2026-10-03 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subject", models.CharField(blank=True, max_length=100)),
                (
                    "class_level",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Primary 4" or "JSS 2".',
                        max_length=100,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="The note, paragraphs separated by a blank line."
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("typed", "Typed or pasted"),
                            ("upload", "Uploaded document"),
                            ("photo", "Photo of a page"),
                            ("ai", "Written with AI"),
                        ],
                        default="typed",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "audio_file",
                    models.FileField(blank=True, upload_to="lesson_audio/%Y/%m/"),
                ),
                ("audio_text", models.TextField(blank=True)),
                ("audio_voice", models.CharField(blank=True, max_length=40)),
                ("audio_duration", models.FloatField(blank=True, null=True)),
                (
                    "audio_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not started"),
                            ("working", "Working"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("audio_error", models.CharField(blank=True, max_length=300)),
                ("audio_updated", models.DateTimeField(blank=True, null=True)),
                (
                    "keywords_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not started"),
                            ("working", "Working"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("keywords_error", models.CharField(blank=True, max_length=300)),
                (
                    "keywords_text",
                    models.TextField(
                        blank=True, help_text="The body the key words were picked from."
                    ),
                ),
                ("keywords_updated", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="KeyWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("word", models.CharField(max_length=80)),
                ("meaning", models.CharField(blank=True, max_length=300)),
                ("ipa", models.CharField(blank=True, max_length=120)),
                ("syllables", models.CharField(blank=True, max_length=120)),
                (
                    "tip",
                    models.CharField(
                        blank=True,
                        help_text="What to listen for when saying it.",
                        max_length=300,
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(blank=True, upload_to="lesson_audio/words/%Y/%m/"),
                ),
                ("added_by_teacher", models.BooleanField(default=False)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("mastered", models.BooleanField(default=False)),
                ("last_heard", models.CharField(blank=True, max_length=120)),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to="lesson_audio.lessonnote",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Usage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("audio", "Audio characters"),
                            ("write", "AI lesson notes"),
                            ("words", "Key word sets"),
                            ("practice", "Practice attempts"),
                            ("read", "Pages read from photos"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount", models.PositiveIntegerField(default=1)),
                ("at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "kind", "at"],
                        name="lesson_audi_user_id_2546b4_idx",
                    )
                ],
            },
        ),
    ]
