# Generated by Django 5.2.6 on 2026-10-03 06:07

import django.db.models.deletion
from django.db import migrations, models


def into_school_libraries(apps, schema_editor):
    """Notes made before the library: they belong to their owner's school."""
    LessonNote = apps.get_model("lesson_audio", "LessonNote")
    for note in LessonNote.objects.select_related("owner").filter(school__isnull=True):
        if note.owner.school_id:
            LessonNote.objects.filter(pk=note.pk).update(school_id=note.owner.school_id)


class Migration(migrations.Migration):

    dependencies = [
        ("lesson_audio", "0001_initial"),
        ("schools", "0007_level_changes"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonnote",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_notes",
                to="schools.school",
            ),
        ),
        migrations.RunPython(into_school_libraries, migrations.RunPython.noop),
    ]
